---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 10.0.0.19
        port: 5000

  rules:
    - name: Say Hello
      condition: event.payload.message == "sakana"
      action:
        run_job_template:
          name: debug_eda
          organization: Default
