---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5050

  rules:
    - name: test Hello
      condition: event.payload.message == "test"
      action:
        run_workflow_template:
          name: test_eda
          organization: Default
