---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  rules:
    - name: test playbook
      condition: event.payload.message == "test3"
      action:
        run_playbook:
          name: debug.yml
